global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'evm-executor'
    static_configs:
      - targets: ['executor:9091']
        labels:
          service: 'evm-executor'
